# Generated by Django 4.0.5 on 2022-08-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accNumber', models.CharField(max_length=200, null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('companyName', models.CharField(max_length=200, null=True)),
                ('accStatus', models.CharField(max_length=200, null=True)),
                ('prntCompany', models.CharField(max_length=200, null=True)),
                ('rollUp', models.CharField(max_length=200, null=True)),
                ('TIN', models.CharField(max_length=200, null=True)),
                ('NatureOfBusiness', models.CharField(max_length=200, null=True)),
                ('AMF', models.CharField(max_length=200, null=True)),
                ('Signatory1', models.CharField(max_length=200, null=True)),
                ('Signatory1Designation', models.CharField(max_length=200, null=True)),
                ('Signatory2', models.CharField(max_length=200, null=True)),
                ('Signatory2Designation', models.CharField(max_length=200, null=True)),
                ('Signatory3', models.CharField(max_length=200, null=True)),
                ('Signatory3Designation', models.CharField(max_length=200, null=True)),
                ('accNumberStreet', models.CharField(max_length=200, null=True)),
                ('accBrgy', models.CharField(max_length=200, null=True)),
                ('accCityProvReg', models.CharField(max_length=200, null=True)),
                ('accZipCode', models.CharField(max_length=200, null=True)),
                ('ContactPerson1', models.CharField(max_length=200, null=True)),
                ('ContactPerson1Designation', models.CharField(max_length=200, null=True)),
                ('ContactPerson1Phone', models.CharField(max_length=200, null=True)),
                ('ContactPerson1Email', models.EmailField(max_length=200, null=True)),
                ('ContactPerson2', models.CharField(max_length=200, null=True)),
                ('ContactPerson2Designation', models.CharField(max_length=200, null=True)),
                ('ContactPerson2Phone', models.CharField(max_length=200, null=True)),
                ('ContactPerson2Email', models.EmailField(max_length=200, null=True)),
                ('FaxNumber1', models.CharField(max_length=200, null=True)),
                ('FaxNumber2', models.CharField(max_length=200, null=True)),
                ('planTypewithDescription1', models.CharField(max_length=200, null=True)),
                ('planTypewithDescription2', models.CharField(max_length=200, null=True)),
                ('planTypewithDescription3', models.CharField(max_length=200, null=True)),
                ('planTypewithDescription4', models.CharField(max_length=200, null=True)),
                ('planTypewithDescription5', models.CharField(max_length=200, null=True)),
                ('planMembershipFee1', models.DecimalField(decimal_places=2, max_digits=60, null=True)),
                ('planMembershipFee2', models.DecimalField(decimal_places=2, max_digits=60, null=True)),
                ('planMembershipFee3', models.DecimalField(decimal_places=2, max_digits=60, null=True)),
                ('planMembershipFee4', models.DecimalField(decimal_places=2, max_digits=60, null=True)),
                ('planMembershipFee5', models.DecimalField(decimal_places=2, max_digits=60, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('PlanTypeBenefitsSummaryReceiveDates', models.CharField(max_length=200, null=True)),
                ('ConformeDate', models.CharField(max_length=200, null=True)),
                ('OriginalEffectiveDate', models.CharField(max_length=200, null=True)),
                ('EffectiveDate', models.CharField(max_length=200, null=True)),
                ('ExpiryDate', models.DateField(blank=True, null=True)),
                ('SuspensionDate', models.CharField(max_length=200, null=True)),
                ('ReactivationDate', models.CharField(max_length=200, null=True)),
                ('TerminationExtensionDate', models.CharField(max_length=200, null=True)),
                ('ModeofPayment', models.CharField(max_length=200, null=True)),
                ('proRatingFee', models.CharField(max_length=200, null=True)),
                ('VatProvision', models.CharField(max_length=200, null=True)),
                ('philHealth', models.CharField(max_length=200, null=True)),
                ('payeeName', models.CharField(max_length=200, null=True)),
                ('NumberStreet', models.CharField(max_length=200, null=True)),
                ('BarangayDistrict', models.CharField(default=' ', max_length=200)),
                ('CityProvinceRegion', models.CharField(default=' ', max_length=200)),
                ('ZipCode', models.CharField(max_length=200, null=True)),
                ('BillingAddressee', models.CharField(default=' ', max_length=200)),
                ('BillingAddresseeDesignation', models.CharField(max_length=200, null=True)),
                ('initialNumberofEmployees', models.BigIntegerField(default=0, null=True)),
                ('initialNumberofImmediateDependents', models.BigIntegerField(default=0, null=True)),
                ('initialNumberofExtendedDependents', models.BigIntegerField(default=0, null=True)),
                ('foreignEmployees', models.CharField(default=0, max_length=200, null=True)),
                ('nationalitiesPositionsofExpatriates', models.CharField(max_length=200, null=True)),
                ('companyNameonCard', models.CharField(max_length=200, null=True)),
                ('remarksInfo', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='accountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accStatus', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilStat', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('companyLocationNumAndStreet', models.CharField(max_length=200)),
                ('companyLocationBarangayAndDistrict', models.CharField(max_length=200, null=True)),
                ('companyCityAndProvince', models.CharField(max_length=200, null=True)),
                ('companyZipCode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memParti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memParti', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memTypeName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modeOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mop', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='parentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prntCompany', models.CharField(max_length=200, null=True)),
                ('prntLocationNumAndStreet', models.CharField(max_length=200)),
                ('prntLocationBarangayAndDistrict', models.CharField(max_length=200, null=True)),
                ('prntCityAndProvince', models.CharField(max_length=200, null=True)),
                ('prntZipCode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='planList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planTypewDescName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prinMem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='relaMem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vatProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmoCardNumber', models.BigIntegerField(null=True, verbose_name='HMO Card Number')),
                ('lastName', models.CharField(max_length=200, null=True, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=200, null=True, verbose_name='First Name')),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('OriginalEffectiveDate', models.DateField(verbose_name='Original Effective Date')),
                ('EffectiveDate', models.DateField(null=True)),
                ('ExpiryDate', models.DateField(null=True)),
                ('SuspensionDate', models.DateField(null=True)),
                ('ReactivationDate', models.DateField(null=True)),
                ('TerminationExtensionDate', models.CharField(max_length=200, null=True)),
                ('BirthDate', models.CharField(max_length=200, null=True)),
                ('Height', models.CharField(max_length=200, null=True)),
                ('Weight', models.CharField(max_length=200, null=True)),
                ('philHealth', models.BooleanField(null=True)),
                ('employeeNum', models.CharField(max_length=200, null=True)),
                ('posAndocu', models.CharField(max_length=200, null=True)),
                ('MemberAddressNumberAndStreet', models.CharField(max_length=200, null=True)),
                ('MemberAddressBarangayAndDistrict', models.CharField(max_length=200, null=True)),
                ('MemberCityProvinceRegion', models.CharField(max_length=200, null=True)),
                ('MemberCityZipCode', models.CharField(max_length=200, null=True)),
                ('MemberContactNumber', models.CharField(max_length=200, null=True)),
                ('remarksMem', models.CharField(max_length=200, null=True)),
                ('CStat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.civilstatus')),
                ('Mop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.modeofpayment')),
                ('accNumberMem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.account', verbose_name='Account Number')),
                ('attachPrinMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.member', verbose_name='Attached Principle Member')),
                ('comName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company', verbose_name='Company Name')),
                ('gen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.gender')),
                ('memStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.accountstatus', verbose_name='Member Status')),
                ('memType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.memtypes', verbose_name='Member Type')),
                ('memberParticipation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.memparti', verbose_name='Member Participation')),
                ('planType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.planlist', verbose_name='Plan Type')),
                ('relationshipPrinMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.relamem', verbose_name='Relationship to Principle Member')),
            ],
        ),
    ]
